"""Read-only tools for inspecting original MASS runtime artifacts."""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Any

from mass_adk.config import load_config


RESULT_SUFFIXES = {".parq", ".pkl"}


def _to_display_path(path: Path) -> str:
    """Return a stable path string for tool responses."""

    try:
        return str(path.relative_to(load_config().mass_root.parent))
    except ValueError:
        return str(path)


def _safe_child(root: Path, child_name: str) -> Path | None:
    """Resolve a direct child path under root without allowing traversal."""

    if not child_name or "/" in child_name or "\\" in child_name:
        return None
    candidate = (root / child_name).resolve()
    try:
        candidate.relative_to(root.resolve())
    except ValueError:
        return None
    return candidate


def _file_summary(path: Path, root: Path) -> dict[str, Any]:
    stat = path.stat()
    try:
        relative_path = str(path.relative_to(root))
    except ValueError:
        relative_path = path.name
    return {
        "name": path.name,
        "relative_path": relative_path,
        "display_path": _to_display_path(path),
        "kind": "distribution" if path.name.startswith("dist_") else "signal_result",
        "extension": path.suffix,
        "size_bytes": stat.st_size,
        "modified_unix": stat.st_mtime,
    }


def validate_mass_runtime_paths() -> dict[str, Any]:
    """Validate configured MASS root, results root, and common dataset paths."""

    config = load_config()
    paths = {
        "mass_root": config.mass_root,
        "results_root": config.results_root,
        "checkpoint_root": config.results_root / "checkpoints",
        "china_sample_dataset": config.mass_root / "sample_data" / "ih_smoke",
        "sp500_sample_dataset": config.mass_root / "sample_data" / "sp500_smoke",
    }
    return {
        "paths": {
            key: {
                "path": str(path),
                "exists": path.exists(),
                "is_dir": path.is_dir(),
            }
            for key, path in paths.items()
        },
        "configured_model": config.model,
        "note": "This tool validates self-contained MASS-ADK paths and does not launch MASS runs.",
    }


def list_mass_result_artifacts(
    stock_pool: str | None = None,
    include_distributions: bool = True,
    limit: int = 50,
) -> dict[str, Any]:
    """List original MASS result artifacts from the configured results root.

    Args:
        stock_pool: Optional filename prefix filter, such as `ih` or `sp500`.
        include_distributions: Whether to include `dist_*.pkl` files.
        limit: Maximum number of artifacts to return.
    """

    config = load_config()
    root = config.results_root
    if not root.exists():
        return {
            "error": "MASS results root does not exist.",
            "results_root": str(root),
            "artifacts": [],
            "count": 0,
        }

    normalized_pool = stock_pool.strip() if stock_pool else None
    artifacts = []
    for path in sorted(root.iterdir(), key=lambda item: item.stat().st_mtime, reverse=True):
        if not path.is_file() or path.suffix not in RESULT_SUFFIXES:
            continue
        if not include_distributions and path.name.startswith("dist_"):
            continue
        if normalized_pool:
            accepted_prefixes = (f"{normalized_pool}_", f"dist_{normalized_pool}_")
            if not path.name.startswith(accepted_prefixes):
                continue
        artifacts.append(_file_summary(path, root))
        if len(artifacts) >= max(1, min(limit, 200)):
            break

    return {
        "results_root": str(root),
        "artifacts": artifacts,
        "count": len(artifacts),
        "filters": {
            "stock_pool": stock_pool,
            "include_distributions": include_distributions,
            "limit": limit,
        },
        "note": "Artifacts are read-only MASS outputs generated by the original runtime.",
    }


def list_mass_checkpoints(stock_pool: str | None = None, limit: int = 50) -> dict[str, Any]:
    """List original MASS checkpoint run directories.

    Args:
        stock_pool: Optional checkpoint-name prefix filter, such as `ih` or `sp500`.
        limit: Maximum number of checkpoint directories to return.
    """

    checkpoint_root = load_config().results_root / "checkpoints"
    if not checkpoint_root.exists():
        return {
            "checkpoint_root": str(checkpoint_root),
            "checkpoints": [],
            "count": 0,
            "error": "MASS checkpoint root does not exist.",
        }

    normalized_pool = stock_pool.strip() if stock_pool else None
    checkpoints = []
    for path in sorted(
        checkpoint_root.iterdir(), key=lambda item: item.stat().st_mtime, reverse=True
    ):
        if not path.is_dir():
            continue
        if normalized_pool and not path.name.startswith(f"{normalized_pool}_"):
            continue
        manifest_path = path / "manifest.json"
        progress_path = path / "progress.json"
        progress = _load_json(progress_path) if progress_path.exists() else {}
        completed_dates = progress.get("completed_dates") or []
        checkpoints.append(
            {
                "run_id": path.name,
                "display_path": _to_display_path(path),
                "has_manifest": manifest_path.exists(),
                "has_progress": progress_path.exists(),
                "completed_dates": completed_dates,
                "completed_date_count": len(completed_dates),
                "current_phase": progress.get("current_phase"),
                "last_committed_date": progress.get("last_committed_date"),
            }
        )
        if len(checkpoints) >= max(1, min(limit, 200)):
            break

    return {
        "checkpoint_root": str(checkpoint_root),
        "checkpoints": checkpoints,
        "count": len(checkpoints),
        "filters": {"stock_pool": stock_pool, "limit": limit},
    }


def _load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def _count_files(path: Path, suffix: str | None = None) -> int:
    if not path.exists() or not path.is_dir():
        return 0
    return sum(
        1
        for item in path.iterdir()
        if item.is_file() and (suffix is None or item.suffix == suffix)
    )


def _sqlite_summary(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"exists": False}
    summary: dict[str, Any] = {"exists": True, "tables": []}
    try:
        with sqlite3.connect(f"file:{path}?mode=ro", uri=True) as connection:
            table_rows = connection.execute(
                "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
            ).fetchall()
            tables = []
            for (table_name,) in table_rows:
                count = connection.execute(
                    f'SELECT COUNT(*) FROM "{table_name}"'
                ).fetchone()[0]
                tables.append({"name": table_name, "row_count": count})
            summary["tables"] = tables
    except sqlite3.Error as exc:
        summary["error"] = str(exc)
    return summary


def inspect_mass_checkpoint(run_id: str) -> dict[str, Any]:
    """Inspect one original MASS checkpoint directory by run id.

    Args:
        run_id: Direct checkpoint directory name from `list_mass_checkpoints`.
    """

    checkpoint_root = load_config().results_root / "checkpoints"
    run_path = _safe_child(checkpoint_root, run_id)
    if run_path is None:
        return {
            "error": "Invalid run_id. Use a direct checkpoint directory name only.",
            "run_id": run_id,
        }
    if not run_path.exists() or not run_path.is_dir():
        return {
            "error": "Checkpoint run directory does not exist.",
            "run_id": run_id,
            "checkpoint_root": str(checkpoint_root),
        }

    manifest_path = run_path / "manifest.json"
    progress_path = run_path / "progress.json"
    manifest = _load_json(manifest_path) if manifest_path.exists() else {}
    progress = _load_json(progress_path) if progress_path.exists() else {}

    return {
        "run_id": run_id,
        "display_path": _to_display_path(run_path),
        "manifest": manifest,
        "progress": progress,
        "artifact_counts": {
            "date_signal_parq": _count_files(run_path / "date_signals", ".parq"),
            "date_optimizer_json": _count_files(run_path / "date_optimizer", ".json"),
            "agent_state_files": _count_files(run_path / "agent_state"),
            "snapshot_files": _count_files(run_path / "snapshots"),
        },
        "sqlite": _sqlite_summary(run_path / "agent_results.sqlite"),
        "interpretation": "A complete smoke checkpoint should have completed_dates, per-date signal shards, optimizer records, and SQLite agent state.",
    }
